vendor: OTR Community
step: 3.B.4
procedure: Used HTTPS to transport C2 (192.168.0.5) traffic
criteria: Evidence that the network data sent over the C2 channel is HTTPS
technique:
  name: Standard Application Layer Protocol
  id: T1071
issue: https://github.com/OTRF/detection-hackathon-apt29/issues/6
detections:
  - main_type: None
    modifier_type:
    description: No detection capability demonstrated for this procedure.
    reference:
    queries:
